# Generated by Django 6.1.1 on 2026-09-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_term"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
