# Generated by Django 6.1.1 on 2026-09-26 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0007_stream"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.school",
            ),
            preserve_default=False,
        ),
    ]
