# Generated by Django 6.1.1 on 2026-09-28 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0011_performance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="marks",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
