# Generated by Django 6.1.1 on 2026-09-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0012_alter_performance_marks"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="performance",
            constraint=models.CheckConstraint(
                condition=models.Q(("marks__gte", 0), ("marks__lte", 100)),
                name="performance_marks_0_100",
            ),
        ),
    ]
