# Generated by Django 6.1.1 on 2026-09-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0013_performance_performance_marks_0_100"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="performance",
            constraint=models.UniqueConstraint(
                fields=("student", "subject", "academic_year", "term"),
                name="unique_student_subject_term_performance",
            ),
        ),
    ]
