# Generated by Django 6.1.1 on 2026-09-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0014_performance_unique_student_subject_term_performance"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="performance",
            name="unique_student_subject_term_performance",
        ),
        migrations.AddField(
            model_name="performance",
            name="assessment_type",
            field=models.CharField(
                choices=[
                    ("opener", "Opener"),
                    ("mid", "Mid-term"),
                    ("end", "End-term"),
                ],
                default="end",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="performance",
            constraint=models.UniqueConstraint(
                fields=(
                    "student",
                    "subject",
                    "academic_year",
                    "term",
                    "assessment_type",
                ),
                name="unique_student_subject_term_performance",
            ),
        ),
    ]
