# Generated by Django 6.1.1 on 2026-09-29 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0016_teacherprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "class_levels",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subject_definitions",
                        to="schools.classlevel",
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subject_definitions",
                        to="schools.curriculum",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("curriculum", "code"),
                        name="unique_subject_code_per_curriculum",
                    )
                ],
            },
        ),
    ]
