# Generated by Django 6.1.1 on 2026-09-29 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0017_subjectdefinition"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurriculumPathway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "class_levels",
                    models.ManyToManyField(
                        blank=True,
                        related_name="curriculum_pathways",
                        to="schools.classlevel",
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pathways",
                        to="schools.curriculum",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="subjectdefinition",
            name="pathways",
            field=models.ManyToManyField(
                blank=True,
                related_name="subject_definitions",
                to="schools.curriculumpathway",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumpathway",
            constraint=models.UniqueConstraint(
                fields=("curriculum", "code"), name="unique_pathway_code_per_curriculum"
            ),
        ),
    ]
