# Generated by Django 6.1.1 on 2026-09-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0018_curriculumpathway_subjectdefinition_pathways_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="school_subjects",
                to="schools.subjectdefinition",
            ),
        ),
    ]
