# Generated by Django 6.1.1 on 2026-10-01 19:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0022_performance_entered_by_performance_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("opener", "Opener"),
                            ("mid", "Mid-term"),
                            ("end", "End-term"),
                        ],
                        default="end",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_average",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("stream_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("class_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("subject_scores", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubjectPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paper_number", models.PositiveSmallIntegerField()),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="performance",
            name="unique_student_subject_term_performance",
        ),
        migrations.AddField(
            model_name="performance",
            name="paper_number",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="performance",
            constraint=models.UniqueConstraint(
                fields=(
                    "student",
                    "subject",
                    "academic_year",
                    "term",
                    "assessment_type",
                    "paper_number",
                ),
                name="unique_student_subject_term_performance",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="class_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exams",
                to="schools.classlevel",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="schools.term",
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="schools.exam",
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_results",
                to="schools.student",
            ),
        ),
        migrations.AddField(
            model_name="subjectpaper",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papers",
                to="schools.subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.UniqueConstraint(
                fields=("term", "assessment_type", "class_level"),
                name="unique_exam_per_term_type_level",
            ),
        ),
        migrations.AddConstraint(
            model_name="examresult",
            constraint=models.UniqueConstraint(
                fields=("exam", "student"), name="unique_result_per_exam_student"
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectpaper",
            constraint=models.UniqueConstraint(
                fields=("subject", "paper_number"), name="unique_paper_per_subject"
            ),
        ),
    ]
