# Generated by Django 6.1.1 on 2026-10-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0023_exam_examresult_subjectpaper_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("school", "admission_number"),
                name="unique_admission_number_per_school",
            ),
        ),
    ]
