# Generated by Django 6.1.1 on 2026-10-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0024_student_admission_unique_per_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="schooladminprofile",
            name="is_deputy",
            field=models.BooleanField(default=False),
        ),
    ]
