# Generated by Django 6.1.1 on 2026-10-07 14:49

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0028_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="county",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="school",
            name="school_type",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="school",
            name="setup_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="sub_county",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="markauditlog",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mark_audit_logs",
                to="schools.school",
            ),
        ),
        migrations.CreateModel(
            name="SchoolRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=20, unique=True)),
                ("school_name", models.CharField(max_length=200)),
                ("proposed_school_code", models.CharField(max_length=50)),
                (
                    "school_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("junior", "Junior school"),
                            ("secondary", "Secondary"),
                            ("combined", "Combined / other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("school_phone", models.CharField(max_length=30)),
                ("school_email", models.EmailField(blank=True, max_length=254)),
                ("county", models.CharField(max_length=100)),
                ("sub_county", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("administrator_name", models.CharField(max_length=200)),
                ("administrator_username", models.CharField(max_length=150)),
                ("administrator_email", models.EmailField(blank=True, max_length=254)),
                ("administrator_phone", models.CharField(max_length=30)),
                ("password_hash", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_verification", "Pending verification"),
                            ("verified", "Verified"),
                            ("pending_approval", "Pending approval"),
                            ("needs_information", "Needs information"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_verification",
                        max_length=30,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("verified", "Verified"),
                        ],
                        default="unverified",
                        max_length=20,
                    ),
                ),
                ("otp_hash", models.CharField(blank=True, max_length=255)),
                ("otp_expires_at", models.DateTimeField(blank=True, null=True)),
                ("otp_attempts", models.PositiveSmallIntegerField(default=0)),
                ("otp_send_count", models.PositiveSmallIntegerField(default=0)),
                ("otp_sent_at", models.DateTimeField(blank=True, null=True)),
                ("authorization_confirmed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("info_request_message", models.TextField(blank=True)),
                ("info_response", models.TextField(blank=True)),
                ("info_responded_at", models.DateTimeField(blank=True, null=True)),
                ("internal_notes", models.TextField(blank=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registration",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "pending_verification",
                                    "verified",
                                    "pending_approval",
                                    "needs_information",
                                ],
                            )
                        ),
                        fields=("proposed_school_code",),
                        name="unique_open_registration_school_code",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("administrator_username"),
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "pending_verification",
                                    "verified",
                                    "pending_approval",
                                    "needs_information",
                                ],
                            )
                        ),
                        name="unique_open_registration_username",
                    ),
                ],
            },
        ),
    ]
